json.id event.id
json.starts_date event.start_date
json.start event.starts_at
json.starts_at event.start_time
json.end_date event.end_date
json.end event.ends_at
json.ends_at event.end_time
json.address event.address
json.city event.city
json.full_address event.full_address
json.lat event.latitude
json.lng event.longitude
